export const REQUESTED_CITY = 'REQUESTED_CITY';
export const REQUESTED_CITY_SUCCEEDED = 'REQUESTED_CITY_SUCCEEDED';
export const REQUESTED_CITY_FAILED = 'REQUESTED_CITY_FAILED';
export const FETCHED_CITY = 'FETCHED_CITY';